import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("logout", "routes/logout.tsx"),
  route("maps", "routes/maps.tsx"),
  route("g/:groupId", "routes/g.$groupId.tsx"),
  route("g/:groupId/schedule", "routes/g.$groupId.schedule.tsx"),
  route("settings", "routes/settings.tsx"),
  route("groups", "routes/groups.tsx"),
  route("groups/:groupId", "routes/groups.$groupId.tsx"),
  route("playground", "routes/playground.tsx"),
  route("playground/:mapId", "routes/playground.$mapId.tsx"),
  route("api/auth/*", "routes/api.auth.$.tsx"),
  route("api/maps", "routes/api.maps.tsx"),
  route("api/maps/:mapId", "routes/api.maps.$mapId.tsx"),
  route("api/maps/:mapId/tokens/:tokenId", "routes/api.maps.$mapId.tokens.$tokenId.tsx"),
  route("api/maps/:mapId/tokens/:tokenId/move", "routes/api.maps.$mapId.tokens.$tokenId.move.tsx"),
  route("api/groups", "routes/api.groups.tsx"),
  route("api/groups/:groupId", "routes/api.groups.$groupId.tsx"),
  route("api/groups/:groupId/members", "routes/api.groups.$groupId.members.tsx"),
  route("api/groups/:groupId/members/:userId", "routes/api.groups.$groupId.members.$userId.tsx"),
  route("api/groups/:groupId/leave", "routes/api.groups.$groupId.leave.tsx"),
  route("api/groups/:groupId/invite", "routes/api.groups.$groupId.invite.tsx"),
  route("invite/group/:token", "routes/invite.group.$token.tsx"),
  route("api/uploadthing", "routes/api.uploadthing.ts"),
  route("api/uploadthing/files", "routes/api.uploadthing.files.ts"),
  route("api/uploads", "routes/api.uploads.tsx"),
  route("characters", "routes/characters.tsx"),
  route("api/characters", "routes/api.characters.tsx"),
  route("api/characters/:characterId", "routes/api.characters.$characterId.tsx"),
  route("api/groups/:groupId/tokens", "routes/api.groups.$groupId.tokens.tsx"),
route("api/groups/:groupId/availability", "routes/api.groups.$groupId.availability.tsx"),
  route("api/groups/:groupId/availability/:id", "routes/api.groups.$groupId.availability.$id.tsx"),
  route("api/groups/:groupId/schedule-votes", "routes/api.groups.$groupId.schedule-votes.tsx"),
  route("api/maps/:mapId/chat", "routes/api.maps.$mapId.chat.tsx"),
  route("api/maps/:mapId/chat/batch", "routes/api.maps.$mapId.chat.batch.tsx"),
  route("api/maps/:mapId/ai", "routes/api.maps.$mapId.ai.tsx"),
  route("api/maps/:mapId/ai-draw", "routes/api.maps.$mapId.ai-draw.tsx"),
  route("api/stripe/checkout", "routes/api.stripe.checkout.ts"),
  route("api/stripe/webhook", "routes/api.stripe.webhook.ts"),
  route("api/stripe/success", "routes/api.stripe.success.ts"),
  route("api/stripe/portal", "routes/api.stripe.portal.ts"),
  route("pricing", "routes/pricing.tsx"),
] satisfies RouteConfig;
