import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("maps", "routes/maps.tsx"),
  route("groups", "routes/groups.tsx"),
  route("groups/:groupId", "routes/groups.$groupId.tsx"),
  route("playground", "routes/playground.tsx"),
  route("playground/:mapId", "routes/playground.$mapId.tsx"),
  route("api/auth/*", "routes/api.auth.$.tsx"),
  route("api/maps", "routes/api.maps.tsx"),
  route("api/maps/:mapId", "routes/api.maps.$mapId.tsx"),
  route("api/maps/:mapId/presence", "routes/api.maps.$mapId.presence.tsx"),
  route("api/maps/:mapId/presence/leave", "routes/api.maps.$mapId.presence.leave.tsx"),
  route("api/groups", "routes/api.groups.tsx"),
  route("api/groups/:groupId", "routes/api.groups.$groupId.tsx"),
  route("api/groups/:groupId/members", "routes/api.groups.$groupId.members.tsx"),
  route("api/groups/:groupId/members/:userId", "routes/api.groups.$groupId.members.$userId.tsx"),
  route("api/groups/:groupId/leave", "routes/api.groups.$groupId.leave.tsx"),
  route("api/groups/:groupId/invite", "routes/api.groups.$groupId.invite.tsx"),
  route("invite/group/:token", "routes/invite.group.$token.tsx"),
  route("api/uploadthing", "routes/api.uploadthing.ts"),
  route("api/uploadthing/files", "routes/api.uploadthing.files.ts"),
] satisfies RouteConfig;
